# Generated by Django 3.0.5 on 2020-09-12 22:01

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200907_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='city',
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default='55 71 9999-9999', max_length=20),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='cover_letter',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='email',
            field=models.EmailField(default='example@gmail.com', max_length=20),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='location',
            field=models.CharField(default='Salvador', max_length=100),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='resume',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=django_countries.fields.CountryField(default='BR', max_length=2),
        ),
        migrations.AlterField(
            model_name='employer',
            name='designation',
            field=models.CharField(default='Employer', max_length=50),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(default='Python', max_length=50)),
                ('jobseeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.JobSeeker')),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_reference', models.URLField(default='github.com', max_length=100)),
                ('jobseeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.JobSeeker')),
            ],
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Resume', 'Resume'), ('Cover Letter', 'Cover Letter'), ('Video', 'Video')], max_length=15)),
                ('file', models.FileField(default='', upload_to='documents')),
                ('jobseeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.JobSeeker')),
            ],
        ),
    ]
